function define(name, value) {
    Object.defineProperty(exports, name, {
        value:      value,
        enumerable: true
    });
}

define("LIST", [
    ["xummy", "dummy"],
    ["dxmmy", "dummy"],
    ["duxmy", "dummy"],
    ["dumxy", "dummy"],
    ["dummx", "dummy"],
    ["xumming", "dumming"],
    ["dxmming", "dumming"],
    ["duxming", "dumming"],
    ["dumxing", "dumming"],
    ["dummxng", "dumming"],
    ["dummixg", "dumming"],
    ["dumminx", "dumming"],
    ["xummingdummingdumming", "dummingdummingdumming"],
    ["dxmmingdummingdumming", "dummingdummingdumming"],
    ["duxmingdummingdumming", "dummingdummingdumming"],
    ["dumxingdummingdumming", "dummingdummingdumming"],
    ["dummxngdummingdumming", "dummingdummingdumming"],
    ["dummixgdummingdumming", "dummingdummingdumming"],
    ["dumminxdummingdumming", "dummingdummingdumming"],
    ["dummingxummingdumming", "dummingdummingdumming"],
    ["dummingdxmmingdumming", "dummingdummingdumming"],
    ["dummingduxmingdumming", "dummingdummingdumming"],
    ["dummingdumxingdumming", "dummingdummingdumming"],
    ["dummingdummxngdumming", "dummingdummingdumming"],
    ["dummingdummixgdumming", "dummingdummingdumming"],
    ["dummingdumminxdumming", "dummingdummingdumming"],
    ["dummingdummingxumming", "dummingdummingdumming"],
    ["dummingdummingdxmming", "dummingdummingdumming"],
    ["dummingdummingduxming", "dummingdummingdumming"],
    ["dummingdummingdumxing", "dummingdummingdumming"],
    ["dummingdummingdummxng", "dummingdummingdumming"],
    ["dummingdummingdummixg", "dummingdummingdumming"],
    ["dummingdummingdumminx", "dummingdummingdumming"],
    ["xxmmingdummingdumming", "dummingdummingdumming"],
    ["dxxmingdummingdumming", "dummingdummingdumming"],
    ["duxxingdummingdumming", "dummingdummingdumming"],
    ["dumxxngdummingdumming", "dummingdummingdumming"],
    ["dummxxgdummingdumming", "dummingdummingdumming"],
    ["dummixxdummingdumming", "dummingdummingdumming"],
    ["dumminxxummingdumming", "dummingdummingdumming"],
    ["dummingxxmmingdumming", "dummingdummingdumming"],
    ["dummingdxxmingdumming", "dummingdummingdumming"],
    ["dummingduxxingdumming", "dummingdummingdumming"],
    ["dummingdumxxngdumming", "dummingdummingdumming"],
    ["dummingdummxxgdumming", "dummingdummingdumming"],
    ["dummingdummixxdumming", "dummingdummingdumming"],
    ["dummingdumminxxumming", "dummingdummingdumming"],
    ["dummingdummingxxmming", "dummingdummingdumming"],
    ["dummingdummingdxxming", "dummingdummingdumming"],
    ["dummingdummingduxxing", "dummingdummingdumming"],
    ["dummingdummingdumxxng", "dummingdummingdumming"],
    ["dummingdummingdummxxg", "dummingdummingdumming"],
    ["dummingdummingdummixx", "dummingdummingdumming"]
]);

