function define(name, value) {
    Object.defineProperty(exports, name, {
        value:      value,
        enumerable: true
    });
}

define("LIST", [
    ["Dummy", "dummy"],
    ["dUmmy", "dummy"],
    ["duMmy", "dummy"],
    ["dumMy", "dummy"],
    ["dummY", "dummy"],
    ["Dumming", "dumming"],
    ["dUmming", "dumming"],
    ["duMming", "dumming"],
    ["dumMing", "dumming"],
    ["dummIng", "dumming"],
    ["dummiNg", "dumming"],
    ["dumminG", "dumming"],
    ["Dummingdummingdumming", "dummingdummingdumming"],
    ["dUmmingdummingdumming", "dummingdummingdumming"],
    ["duMmingdummingdumming", "dummingdummingdumming"],
    ["dumMingdummingdumming", "dummingdummingdumming"],
    ["dummIngdummingdumming", "dummingdummingdumming"],
    ["dummiNgdummingdumming", "dummingdummingdumming"],
    ["dumminGdummingdumming", "dummingdummingdumming"],
    ["dummingDummingdumming", "dummingdummingdumming"],
    ["dummingdUmmingdumming", "dummingdummingdumming"],
    ["dummingduMmingdumming", "dummingdummingdumming"],
    ["dummingdumMingdumming", "dummingdummingdumming"],
    ["dummingdummIngdumming", "dummingdummingdumming"],
    ["dummingdummiNgdumming", "dummingdummingdumming"],
    ["dummingdumminGdumming", "dummingdummingdumming"],
    ["dummingdummingDumming", "dummingdummingdumming"],
    ["dummingdummingdUmming", "dummingdummingdumming"],
    ["dummingdummingduMming", "dummingdummingdumming"],
    ["dummingdummingdumMing", "dummingdummingdumming"],
    ["dummingdummingdummIng", "dummingdummingdumming"],
    ["dummingdummingdummiNg", "dummingdummingdumming"],
    ["dummingdummingdumminG", "dummingdummingdumming"],
    ["DUmmingdummingdumming", "dummingdummingdumming"],
    ["dUMmingdummingdumming", "dummingdummingdumming"],
    ["duMMingdummingdumming", "dummingdummingdumming"],
    ["dumMIngdummingdumming", "dummingdummingdumming"],
    ["dummINgdummingdumming", "dummingdummingdumming"],
    ["dummiNGdummingdumming", "dummingdummingdumming"],
    ["dumminGDummingdumming", "dummingdummingdumming"],
    ["dummingDUmmingdumming", "dummingdummingdumming"],
    ["dummingdUMmingdumming", "dummingdummingdumming"],
    ["dummingduMMingdumming", "dummingdummingdumming"],
    ["dummingdumMIngdumming", "dummingdummingdumming"],
    ["dummingdummINgdumming", "dummingdummingdumming"],
    ["dummingdummiNGdumming", "dummingdummingdumming"],
    ["dummingdumminGDumming", "dummingdummingdumming"],
    ["dummingdummingDUmming", "dummingdummingdumming"],
    ["dummingdummingdUMming", "dummingdummingdumming"],
    ["dummingdummingduMMing", "dummingdummingdumming"],
    ["dummingdummingdumMIng", "dummingdummingdumming"],
    ["dummingdummingdummINg", "dummingdummingdumming"],
    ["dummingdummingdummiNG", "dummingdummingdumming"]
]);

